language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run src:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: src/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
